# Generated by Django 3.0 on 2022-11-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('phone', models.CharField(max_length=20, verbose_name='用户手机')),
                ('password', models.CharField(max_length=32, verbose_name='明文密码')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
            ],
        ),
    ]
