# Generated by Django 4.1 on 2022-11-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="username",
            field=models.CharField(default="user", max_length=32, verbose_name="用户名"),
            preserve_default=False,
        ),
    ]
