# Generated by Django 3.0 on 2022-11-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('gid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('release', models.DateField()),
                ('showcase', models.TextField()),
                ('images', models.TextField()),
                ('setup', models.TextField()),
            ],
        ),
    ]
