# Generated by Django 3.0 on 2022-11-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.BigAutoField(primary_key=True, serialize=False)),
                ('gid', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
