# Generated by Django 3.0 on 2022-11-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='gid',
            field=models.IntegerField(verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='oid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='订单ID'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='uid',
            field=models.IntegerField(verbose_name='用户ID'),
        ),
    ]
